name: Cypress Git Actions Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Setup node
        uses: actions/setup-node@v4.0.1
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with: 
          start: npm start
